apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pocketmine.fullname" . }}
  labels:
    {{- include "pocketmine.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "pocketmine.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "pocketmine.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "pocketmine.serviceAccountName" . }}
      volumes:
      - name: config
        configMap:
          name: pocketmine
      - name: plugins

      initContainers:
        - name: {{ .Chart.Name }}-plugins
          image: curlimages/curl:7.69.1
          workingDir: /plugins
          command: ["curl"]
          args: ["-LO", "https://poggit.pmmp.io/r/71323/MultiWorld.phar"]
          volumeMounts:
            - name: plugins
              mountPath: /plugins
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: plugins
              mountPath: /plugins
          volumeMounts:
          - name: config
            mountPath: /data/server.properties
            subPath: server.properties
          - name: config
            mountPath: /data/pocketmine.yml
            subPath: pocketmine.yml
          - name: config
            mountPath: /data/ops.txt
            subPath: ops.txt
          ports:
            - name: udp
              containerPort: 19132
              protocol: UDP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
