apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: worlds
spec:
  storageClassName: {{ Values.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi