{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "pocketmine.serviceAccountName" . }}
  labels:
{{ include "pocketmine.labels" . | nindent 4 }}
{{- end -}}
